# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# For SEO, see: https://github.com/jekyll/jekyll-seo-tag
# Keep descriptions to ~155 characters: https://moz.com/learn/seo/meta-description
title: Wild Aviation Services
description: |
    Wild Aviation Services provides Aftermarket Dash-8 service and parts for Oceania and worldwide from Cairns Australia, 24/7. Logistics, material handling and aviation ownership experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wildaviationservices.com.au" # the base hostname & protocol for your site
logo: "/assets/images/logo.png"
imageurl: "/assets/images/"
javascriptsurl: "/assets/javascripts/"
google-analytics: UA-
twitter:
    username: patternworks #twitter:site
author:
    twitter: patternworks #twitter:creator

# Defaults

# Collections

# Markdown settings
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

# Build settings
exclude:
- assets/_source
- CNAME
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
- README.md
- TODO.md
- DESCRIPTION.md

# Plugin settings
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
